const ShopActionTypes = {
  FETCH_COLLECTION: 'FETCH_COLLECTION',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  APPLY_FILTERS: 'APPLY_FILLTERS',
};

export default ShopActionTypes;
