// eslint-disable-next-line import/prefer-default-export
export const data = [
  {
    id: 1,
    name: 'Floppy Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5497_4586_109_f?$PDP-1910L$',
    price: 22,
    similarProducts: [2, 3, 4],
    description: ['Seashell trim',
      'Wide brim', 'Imported'],
    type: 'hats',
    brand: 'aerie',
  },
  {
    id: 2,
    name: 'Bucket Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5497_4588_100_f?$PDP-1910L$',
    price: 18,
    similarProducts: [1, 3, 5],
    description: ['Frayed edges', '100% Cotton',
      'Imported'],
    type: 'hats',
    brand: 'aerie',
  },
  {
    id: 3,
    name: 'Panama Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5497_4562_109_f?$PDP-1910L$',
    price: 20.95,
    similarProducts: [4, 5, 7],
    description: ['100% Paper',
      'Imported'],
    type: 'hats',
    brand: 'aerie',
  },
  {
    id: 4,
    name: 'Baseball Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5497_4795_286_f?$PDP-1910L$',
    price: 25,
    similarProducts: [6, 7, 8],
    description: ['Soft cotton hat with baseball silhouette',
      'Distressed deets for a lived-in & loved look',
      'Graphic at front', '100% Cotton',
      'Imported'],
    type: 'hats',
    brand: 'aerie',
  },
  {
    id: 5,
    name: 'Pit Panthers Baseball Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/1052_5966_100_f?$PDP-1910L$',
    price: 19,
    similarProducts: [4, 6, 7],
    description: ['Hip hop design',
      'Flat bill',
      'Custom print'],
    type: 'hats',
    brand: 'ae',
  },
  {
    id: 6,
    name: 'Striped Straw Bucket Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5497_4565_437_f?$PDP-1910L$',
    price: 18.75,
    similarProducts: [7, 8, 9],
    description: ['100% Paper',
      'Imported'],
    type: 'hats',
    brand: 'aerie',
  },
  {
    id: 7,
    name: '47 Brand NYY Tonal Clean Up Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5421_1359_100_f?$PDP-1910L$',
    price: 24,
    similarProducts: [2, 3, 6],
    description: ['Embroidered NY Yankees logo',
      'Adjustable backstrap', '100% Cotton',
      'Imported'],
    type: 'hats',
    brand: 'ae',
  },
  {
    id: 8,
    name: 'Tropical Bucket Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0422_1235_900_f?$PDP-1910L$',
    price: 14.55,
    similarProducts: [1, 3, 5],
    description: ['Tropical design', '100% Cotton',
      'Imported'],
    type: 'hats',
    brand: 'ae',
  },
  {
    id: 9,
    name: 'Unisex Leopard Bucket Hat',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0422_1279_900_f?$PDP-1910L$',
    price: 16,
    similarProducts: [4, 6, 8],
    description: ['Leopard print', '100% Cotton', 'Machine wash',
      'Imported'],
    type: 'hats',
    brand: 'ae',
  },
  {
    id: 10,
    name: 'High-Waisted Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0326_3957_937_f?$PDP-1910L$',
    price: 61,
    size: ['XS', 'S', 'L', 'XXL'],
    similarProducts: [11, 13, 15],
    description: [
      'Our softest, stretchiest, never-loses-its-shape denim',
      'Super soft, super comfortable and breathable denim', 'Light wash', 'Ripped',
      'Super high-waisted fit'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 11,
    name: 'High-Waisted Jegging Crop',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0324_3951_408_f?$PDP-1910L$',
    price: 29.65,
    size: ['XS', 'S', 'L', 'XL'],
    similarProducts: [12, 13, 16],
    description: ['Our softest, stretchiest, never-loses-its-shape denim',
      'Super soft, super comfortable and breathable denim', 'Light wash -  - wear it like you mean it',
      'Highest waist sits at the natural waist'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 12,
    name: 'Curvy High-Waisted Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0328_3862_329_f?$PDP-1910L$',
    price: 28,
    size: ['M', 'L', 'XL'],
    similarProducts: [11, 14, 16],
    description: ['Our softest, stretchiest, never-loses-its-shape denim',
      'Super soft, super comfortable and breathable denim', 'Camo print',
      'If you are in between sizes you may want to size down | More room through hip & thigh'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 13,
    name: 'Ne(xt) Level High-Waisted Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0327_3740_272_f?$PDP-1910L$',
    price: 52,
    size: ['S', 'M'],
    similarProducts: [10, 12, 15],
    description: ['Super Stretch | Super Soft',
      'The ultimate comfort of a soft pant with the look of your favorite jeasn',
      'Holds its shape & won\'t bag out. Ever.',
      'Color wash'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 14,
    name: 'Ne(xt) Level Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0431_2690_985_f?$PDP-1910L$',
    price: 59.95,
    size: ['XS', 'M', 'XXL'],
    similarProducts: [13, 16, 17],
    description: ['Ne(x)t Level Stretch | Super Soft',
      'Our softest, stretchiest, never-loses-its-shape denim',
      'The ultimate comfort of soft pants with the look of your favorite jeans',
      'Won\'t bag out. Ever.',
      'Medium wash & ripped'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 15,
    name: 'Flex Slim Straight Pant',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/2129_3956_269_f?$PDP-1910L$',
    price: 37.56,
    size: ['XS', 'S', 'L', 'XL'],
    similarProducts: [12, 14, 17],
    description: ['Flex',
      'Flex moves in every direction for max comfort and range of motion',
      'High stretch level that keeps its shape',
      'Five pockets | Interior cell phone pocket',
      'Dyed for softness, even more comfort and one-of-a-kind color',
      'Slim through thigh and leg'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 16,
    name: 'Ne(xt) Level Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0431_2649_416_f?$PDP-1910L$',
    price: 69.75,
    size: ['S', 'M', 'XL', 'XXL'],
    similarProducts: [10, 15, 17],
    description: ['Ne(x)t Level Stretch | Super Soft',
      'Our softest, stretchiest, never-loses-its-shape denim',
      'The ultimate comfort of soft pants with the look of your favorite jeans',
      'Won\'t bag out. Ever.'],
    type: 'jeans',
    brand: 'ae',
  },
  {
    id: 17,
    name: 'Ne(xt) Level Super High-Waisted Jegging',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/3435_2192_003_f?$PDP-1910L$',
    price: 35,
    size: ['XS', 'S', 'L', 'XXL'],
    similarProducts: [14, 12, 11],
    description: ['Super Stretch',
      'Soft with an authentic denim look and juuust the right amount of stretch',
      'Holds its shape & won\'t bag out. Ever.',
      'Limitless stretch waistband for a flattering, gap-free fit',
      'Black wash',
      'Ripped'],
    type: 'jeans',
    brand: 'ae',
  }, {
    id: 18,
    name: 'Moto Jacket',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0383_2485_073_f?$PDP-1910L$',
    price: 69.97,
    size: ['XS', 'L', 'XL'],
    similarProducts: [19, 20, 21],
    description: ['Faux leather',
      'Notched collar',
      'Long sleeves',
      'Zip-up front'],
    type: 'jackets',
    brand: 'ae',
  },
  {
    id: 19,
    name: 'Hemp Denim Jacket',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0383_2966_915_f?$PDP-1910L$',
    price: 98.95,
    size: ['XS', 'S', 'M', 'L'],
    similarProducts: [20, 21, 22],
    description: ['Made from soft wash denim & natural hemp',
      'Collar neck',
      'Long sleeves',
      'Button-up front',
      'Chest pockets',
      'Side pockets', 'Relaxed fit: cut for extra comfort, but not too baggy',
      'Cropped length'],
    type: 'jackets',
    brand: 'ae',
  },
  {
    id: 20,
    name: 'Corduroy Jacket',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0383_2671_615_f?$PDP-1910L$',
    price: 45.67,
    size: ['XS', 'S'],
    similarProducts: [18, 19, 21],
    description: ['Made from soft corduroy',
      'Collar neck',
      'Button front',
      'Chest pockets',
      'Side pockets',
      'Classic fit: the essential fit for that so right feeling',
      'Classic length: hits below top of waistband'],
    type: 'jackets',
    brand: 'ae',
  },
  {
    id: 21,
    name: 'Twill Cropped Jacket',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/5495_1737_141_f?$PDP-1910L$',
    price: 41.25,
    size: ['XS', 'L', 'XL'],
    similarProducts: [19, 20, 22],
    description: ['Collar neck',
      'Button front',
      'Chest pockets',
      'Side pockets',
      'Classic fit: the essential fit for that so right feeling',
      'Classic length: hits below top of waistband'],
    type: 'jackets',
    brand: 'aerie',
  },
  {
    id: 22,
    name: 'Fitted Denim Jacket',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0383_2843_400_f?$PDP-1910L$ ',
    price: 35,
    size: ['S', 'M', 'L', 'XL'],
    similarProducts: [18, 19, 21],
    description: ['Made from soft wash denim',
      'Collared neck',
      'Button-up front',
      'Side pockets',
      'Chest pockets',
      'Back graphic',
      'Fitted',
    ],
    type: 'jackets',
    brand: 'ae',
  }, {
    id: 23,
    name: 'Snakeskin Slip On Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0414_4662_020_b?$PDP-1910L$',
    price: 29.95,
    size: [36, 37, 38, 39, 40],
    similarProducts: [24, 26, 27],
    description: [
      'Slip-on',
      'Snakeskin design',
      '48.6% Polyester, 37.1% Cotton, 14.3% Rayon',
      'Imported',
    ],
    type: 'sneakers',
    brand: 'ae',
  },
  {
    id: 24,
    name: 'New Balance Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0722_5416_133_b?$PDP-1910L$',
    price: 81,
    size: [36, 37, 38, 41],
    similarProducts: [25, 26, 28],
    description: ['Updated upper design',
      'IMEVA midsole to deliver lightweight comfort all day long', '25% Rubber, 40% Leather, 35% Other fibers',
      'Imported'],
    type: 'sneakers',
    brand: 'aerie',
  },
  {
    id: 25,
    name: 'New Balance 997 Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0722_4668_142_b?$PDP-1910L$',
    price: 70.55,
    size: [38, 39, 40],
    similarProducts: [26, 28, 29],
    description: ['Updated upper design',
      'IMEVA midsole to deliver lightweight comfort all day long', '25% Rubber, 40% Leather, 35% Other fibers',
      'Imported'],
    type: 'sneakers',
    brand: 'aerie',
  },
  {
    id: 26,
    name: 'X-Racer Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0722_5417_001_b?$PDP-1910L$',
    price: 89.95,
    size: [37, 38, 39, 41],
    similarProducts: [25, 27, 28],
    description: ['Heritage-inspired upper enhanced by no-sew overlays',
      'Synthetic upper material',
      'Premium ABZORB dual-density midsole foam', '25% Rubber, 40% Leather, 35% Other fibers',
      'Imported'],
    type: 'sneakers',
    brand: 'aerie',
  },
  {
    id: 27,
    name: 'Hierro V5 Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/3211_7117_700_b?$PDP-1910L$',
    price: 112.75,
    size: [36, 37, 38, 39],
    similarProducts: [24, 26, 29],
    description: ['Synthetic upper',
      'Fresh Foam innovative midsole',
      'Vibram outsole provides maximum surface contact & multi-directional traction',
      'Imported'],
    type: 'sneakers',
    brand: 'ae',
  },
  {
    id: 28,
    name: 'K-Swiss Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/7412_4632_109_b?$PDP-1910L$',
    price: 70,
    size: [37, 39, 40],
    similarProducts: [23, 24, 25],
    description: ['Leather upper',
      'Textile collar lining',
      'Rubber outsole',
      'Die-cut EVA midsole',
      'Molded EVA sockliner'],
    type: 'sneakers',
    brand: 'ae',
  },
  {
    id: 29,
    name: 'Seavees Sneaker',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/7412_9953_410_b?$PDP-1910L$',
    price: 72.65,
    size: [36, 38, 40, 41],
    similarProducts: [23, 26, 28],
    description: ['Smooth poplin twill',
      'Contoured footbed',
      'Herringbone outsole',
      'Lace up sneaker'],
    type: 'sneakers',
    brand: 'ae',
  },
  {
    id: 30,
    name: 'Maxi Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0703_1013_690_f?$PDP-1910L$',
    price: 28.85,
    size: ['XS', 'S', 'M'],
    similarProducts: [31, 32, 33],
    description: ['Soft, breezy gauze',
      'Elastic smocked waistband with drawstring',
      'Maxi length',
      '100% Cotton',
      'Machine wash'],
    type: 'skirts',
    brand: 'aerie',
  },
  {
    id: 31,
    name: 'Nylon Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/1705_4986_073_b?$PDP-1910L$',
    price: 27.55,
    size: ['XS', 'L', 'XXL'],
    similarProducts: [33, 34, 35],
    description: ['Made from a lightweight fabric blend for an easy touch',
      'Slit detail so you can move your way', 'Fitted: made to move with you',
      'High-waisted',
      ' Mini length'],
    type: 'skirts',
    brand: 'aerie',
  },
  {
    id: 32,
    name: 'Ribbed Knit Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0703_4895_365_b?$PDP-1910L$',
    price: 25,
    size: ['XS', 'M', 'L', 'XL', 'XXL'],
    similarProducts: [33, 34, 35],
    description: ['Soft, ribbed fabric',
      ' Wide waistband',
      'Side slits', 'Midi length', 'Machine wash'],
    type: 'skirts',
    brand: 'aerie',
  },
  {
    id: 33,
    name: 'Chiffon Midi Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/0703_4770_437_b?$PDP-1910L$',
    price: 21,
    size: ['XS', 'S', 'M', 'L'],
    similarProducts: [31, 32, 35],
    description: ['Pretty, flowy chiffon fabric',
      'Lined for extra coverage (!!!)',
      'Cute tiered vibes',
      'Elastic waistband', 'Midi length', 'Machine wash'],
    type: 'skirts',
    brand: 'aerie',
  },
  {
    id: 34,
    name: 'A-Line Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/9332_5579_538_f?$PDP-1910L$',
    price: 26.95,
    size: ['XS', 'M', 'L', 'XXL'],
    similarProducts: [35, 36, 37],
    description: ['Super Stretch',
      'Gives the right amount of structure',
      'Holds its shape & won\'t bag out. Ever.',
      'Medium wash - wear it like you mean it',
      'Button front design', 'A-line fit'],
    type: 'skirts',
    brand: 'ae',
  },
  {
    id: 35,
    name: 'Corduroy A-Line Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/9332_5807_217_f?$PDP-1910L$',
    price: 29.45,
    size: ['S', 'M', 'L', 'XL'],
    similarProducts: [31, 32, 34],
    description: ['Super Stretch',
      'Stretch corduroy in a wider wale',
      'Rich color design',
      'Front pockets',
      'Button front', 'High-waisted fit'],
    type: 'skirts',
    brand: 'ae',
  },
  {
    id: 36,
    name: 'High-Waisted Mini Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/8332_5814_309_f?$PDP-1910L$',
    price: 34.95,
    size: ['XS', 'S', 'M', 'XXL'],
    similarProducts: [34, 35, 37],
    description: ['Ne(x)t Level Stretch',
      'Our softest, never-loses-its-shape denim',
      'Super soft, super flexible, & beyond comfortable!',
      'Camo yoke front & back pockets',
      'Front & back pockets', 'High-waisted fit'],
    type: 'skirts',
    brand: 'ae',
  },
  {
    id: 37,
    name: 'Denim Mini Skirt',
    imageUrl: '//s7d2.scene7.com/is/image/aeo/9332_5839_936_f?$PDP-1910L$',
    price: 39,
    size: ['XS', 'S', 'L', 'XL'],
    similarProducts: [32, 34, 36],
    description: ['Stretch',
      'Mid-weight structure denim with just enough stretch for everyday comfort',
      'The look of your favorite vintage denim with the stretch you know and love',
      'Medium wash - wear it like you mean it',
      'Frayed hem',
      'Super high-waisted fit'],
    type: 'skirts',
    brand: 'ae',
  },
];
